"""Add checkout fields

Revision ID: de79101065db
Revises: d596920f2420
Create Date: 2025-06-03 12:19:40.473055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de79101065db'
down_revision: Union[str, None] = 'd596920f2420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('checked_out', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('patron_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'patron_name')
    op.drop_column('books', 'checkout_date')
    op.drop_column('books', 'due_date')
    op.drop_column('books', 'checked_out')
    # ### end Alembic commands ###
